rtm-vehicle-status:
  secretKey: 823b2f967cae6e05b6bd76b10826ff3b
  appkey: 4299765026
  tenantId: audiNational
  enableShowData: false
  enableService:
    vehicleStatusService: true  #车况存hbase
    vehicleDiagnosisService: false  #告警存hbase
    vehicleAlarmService: false  #告警快照存MySQL
  hbase:
    zkQuorum:
    master:
    clientPort:
    vehiceStatusTable: audi:rtmVehiceStatusData
    vehicleDiagnosisTable: audi:rtmVehicleDiagnosisData
    hbaseSitePath: D:\\timafawvw\\hbaseTmp\\hbase-site.xml
    krb5ConfPath: D:\\timafawvw\\hbaseTmp\\krb5.conf
    userName: audi
    userKeytabPath: D:\\timafawvw\\hbaseTmp\\audi.keytab

