server:
  port: 80
spring:
  datasource:
    max-active: 10
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 5
      min-idle: 0
      password: root
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 10
      max-idle: 5
      min-idle: 0
      password: root
      url: jdbc:mysql://localhost:3306/good?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
